# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # Utility class for OAuth 2 authorization and token management.
  class PetstoreAuth < CoreLibrary::HeaderAuth
    include CoreLibrary
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'PetstoreAuth: OAuthToken is undefined or expired.'
    end

    # Initialization constructor.
    def initialize(petstore_auth_credentials, config)
      auth_params = {}
      @_oauth_client_id = petstore_auth_credentials.oauth_client_id unless
        petstore_auth_credentials.nil? || petstore_auth_credentials.oauth_client_id.nil?
      @_oauth_redirect_uri = petstore_auth_credentials.oauth_redirect_uri unless
        petstore_auth_credentials.nil? || petstore_auth_credentials.oauth_redirect_uri.nil?
      @_oauth_token = petstore_auth_credentials.oauth_token unless
        petstore_auth_credentials.nil? || petstore_auth_credentials.oauth_token.nil?
      @_oauth_scopes = petstore_auth_credentials.oauth_scopes unless
        petstore_auth_credentials.nil? || petstore_auth_credentials.oauth_scopes.nil?
      @_o_auth_api = OauthAuthorizationApi.new(config)
      auth_params[:Authorization] = "Bearer #{@_oauth_token.access_token}" unless @_oauth_token.nil?

      super auth_params
    end

    # Validates the oAuth token.
    # @return [Boolean] true if the token is present and not expired.
    def valid
      !@_oauth_token.nil? && !token_expired?(@_oauth_token)
    end

    # Builds and returns an authorization URL.
    # The user is expected to obtain an authorization code from this URL and then call the
    # fetch token function with that authorization code.
    # @param [String] state An opaque state string.
    # @param [Hash] additional_params Any additional query parameters to be added to the URL.
    # @return [String] The authorization URL.
    def get_authorization_url(state: nil, additional_params: nil)
      auth_url = @_config.get_base_uri_executor.call(Server::AUTH_SERVER)
      auth_url += '/authorize'
      query_params = {
        'response_type' => 'code',
        'client_id' => @_oauth_client_id,
        'redirect_uri' => @_oauth_redirect_uri
      }
      query_params['scope'] = Array(@_o_auth_scopes).compact.join(' ') if @_o_auth_scopes
      query_params['state'] = state if state
      query_params.merge!(additional_params) if additional_params
      auth_url = APIHelper.append_url_with_query_parameters(auth_url,
                                                            query_params)
      APIHelper.clean_url(auth_url)
    end

    # Checks if OAuth token has expired.
    # @param [OAuthToken] token The oAuth token instance.
    # @return [Boolean] true if the token is present and not expired.
    def token_expired?(token)
      token.respond_to?('expiry') && AuthHelper.token_expired?(token.expiry)
    end
  end

  # Data class for PetstoreAuthCredentials.
  class PetstoreAuthCredentials
    attr_reader :oauth_client_id, :oauth_redirect_uri, :oauth_token,
                :oauth_scopes

    def initialize(oauth_client_id:, oauth_redirect_uri:, oauth_token: nil,
                   oauth_scopes: nil)
      raise ArgumentError, 'oauth_client_id cannot be nil' if oauth_client_id.nil?
      raise ArgumentError, 'oauth_redirect_uri cannot be nil' if oauth_redirect_uri.nil?

      @oauth_client_id = oauth_client_id
      @oauth_redirect_uri = oauth_redirect_uri
      @oauth_token = oauth_token
      @oauth_scopes = oauth_scopes
    end

    def self.from_env
      oauth_client_id = ENV['PETSTORE_AUTH_OAUTH_CLIENT_ID']
      oauth_redirect_uri = ENV['PETSTORE_AUTH_OAUTH_REDIRECT_URI']
      oauth_scopes = ENV['PETSTORE_AUTH_OAUTH_SCOPES']
      all_nil = [
        oauth_client_id,
        oauth_redirect_uri
      ].all?(&:nil?)
      return nil if all_nil

      new(oauth_client_id: oauth_client_id,
          oauth_redirect_uri: oauth_redirect_uri, oauth_scopes: oauth_scopes)
    end

    def clone_with(oauth_client_id: nil, oauth_redirect_uri: nil,
                   oauth_token: nil, oauth_scopes: nil)
      oauth_client_id ||= self.oauth_client_id
      oauth_redirect_uri ||= self.oauth_redirect_uri
      oauth_token ||= self.oauth_token
      oauth_scopes ||= self.oauth_scopes

      PetstoreAuthCredentials.new(oauth_client_id: oauth_client_id,
                                  oauth_redirect_uri: oauth_redirect_uri,
                                  oauth_token: oauth_token,
                                  oauth_scopes: oauth_scopes)
    end
  end
end
