# cypress_test_api
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

class HttpResponseCatcher < CypressTestApi::HttpCallBack
  attr_reader :response

  def on_before_request(request)
  end

  # Catching the response
  def on_after_response(response)
    @response = response
  end
end



