# swagger_petstore
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module SwaggerPetstore
  # Order Status
  class Status1Enum
    STATUS1_ENUM = [
      # TODO: Write general description for PLACED
      PLACED = 'placed'.freeze,

      # TODO: Write general description for APPROVED
      APPROVED = 'approved'.freeze,

      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS1_ENUM.include?(value)
    end

    def self.from_value(value, default_value = PLACED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'placed' then PLACED
      when 'approved' then APPROVED
      when 'delivered' then DELIVERED
      else
        default_value
      end
    end
  end
end
