# swagger_petstore
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module SwaggerPetstore
  # pet status in the store
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'available'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze,

      # TODO: Write general description for SOLD
      SOLD = 'sold'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS_ENUM.include?(value)
    end

    def self.from_value(value, default_value = AVAILABLE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'available' then AVAILABLE
      when 'pending' then PENDING
      when 'sold' then SOLD
      else
        default_value
      end
    end
  end
end
