# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Address Model.
  class Address < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :street

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['street'] = 'street'
      @_hash['city'] = 'city'
      @_hash['zip'] = 'zip'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        zip
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(street:, city:, zip: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @street = street
      @city = city
      @zip = zip unless zip == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      street = hash.key?('street') ? hash['street'] : nil
      city = hash.key?('city') ? hash['city'] : nil
      zip = hash.key?('zip') ? hash['zip'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Address.new(street: street,
                  city: city,
                  zip: zip,
                  additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Address | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.street,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.city,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['street'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['city'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} street: #{@street}, city: #{@city}, zip: #{@zip}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} street: #{@street.inspect}, city: #{@city.inspect}, zip: #{@zip.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
