# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # AuditLogEvent Model.
  class AuditLogEvent < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [EventType3]
    attr_accessor :event_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :actor

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :action

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :context

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['event_type'] = 'eventType'
      @_hash['actor'] = 'actor'
      @_hash['action'] = 'action'
      @_hash['context'] = 'context'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        event_type
        actor
        action
        context
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(event_type: SKIP, actor: SKIP, action: SKIP, context: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @event_type = event_type unless event_type == SKIP
      @actor = actor unless actor == SKIP
      @action = action unless action == SKIP
      @context = context unless context == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      event_type = hash.key?('eventType') ? hash['eventType'] : SKIP
      actor = hash.key?('actor') ? hash['actor'] : SKIP
      action = hash.key?('action') ? hash['action'] : SKIP
      context = hash.key?('context') ? hash['context'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      AuditLogEvent.new(event_type: event_type,
                        actor: actor,
                        action: action,
                        context: context,
                        additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [AuditLogEvent | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} event_type: #{@event_type}, actor: #{@actor}, action: #{@action}, context:"\
      " #{@context}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} event_type: #{@event_type.inspect}, actor: #{@actor.inspect}, action:"\
      " #{@action.inspect}, context: #{@context.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
