# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # CreateOrderRequest Model.
  class CreateOrderRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique identifier for the customer
    # @return [String]
    attr_accessor :customer_id

    # Unique identifier for the customer
    # @return [Array[OrderItem]]
    attr_accessor :items

    # URL to receive callback notifications
    # @return [String]
    attr_accessor :callback_url

    # Binary file upload
    # @return [Binary]
    attr_accessor :document

    # Additional order metadata
    # @return [Object]
    attr_accessor :metadata

    # Additional order metadata
    # @return [Hash[String, String]]
    attr_accessor :attributes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['customer_id'] = 'customerId'
      @_hash['items'] = 'items'
      @_hash['callback_url'] = 'callbackUrl'
      @_hash['document'] = 'document'
      @_hash['metadata'] = 'metadata'
      @_hash['attributes'] = 'attributes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        document
        metadata
        attributes
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(customer_id:, items:, callback_url:, document: SKIP,
                   metadata: SKIP, attributes: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @customer_id = customer_id
      @items = items
      @callback_url = callback_url
      @document = document unless document == SKIP
      @metadata = metadata unless metadata == SKIP
      @attributes = attributes unless attributes == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      customer_id = hash.key?('customerId') ? hash['customerId'] : nil
      # Parameter is an array, so we need to iterate through it
      items = nil
      unless hash['items'].nil?
        items = []
        hash['items'].each do |structure|
          items << (OrderItem.from_hash(structure) if structure)
        end
      end

      items = nil unless hash.key?('items')
      callback_url = hash.key?('callbackUrl') ? hash['callbackUrl'] : nil
      document = hash.key?('document') ? hash['document'] : SKIP
      metadata = hash.key?('metadata') ? hash['metadata'] : SKIP
      attributes = hash.key?('attributes') ? hash['attributes'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      CreateOrderRequest.new(customer_id: customer_id,
                             items: items,
                             callback_url: callback_url,
                             document: document,
                             metadata: metadata,
                             attributes: attributes,
                             additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} customer_id: #{@customer_id}, items: #{@items}, callback_url:"\
      " #{@callback_url}, document: #{@document}, metadata: #{@metadata}, attributes:"\
      " #{@attributes}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} customer_id: #{@customer_id.inspect}, items: #{@items.inspect},"\
      " callback_url: #{@callback_url.inspect}, document: #{@document.inspect}, metadata:"\
      " #{@metadata.inspect}, attributes: #{@attributes.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
