# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module WebhooksAndCallbacksApi
  # DeliveryDetails Model.
  class DeliveryDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :method

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :eta

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['method'] = 'method'
      @_hash['eta'] = 'eta'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        method
        eta
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(method: SKIP, eta: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @method = method unless method == SKIP
      @eta = eta unless eta == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      method = hash.key?('method') ? hash['method'] : SKIP
      eta = if hash.key?('eta')
              (DateTimeHelper.from_rfc3339(hash['eta']) if hash['eta'])
            else
              SKIP
            end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      DeliveryDetails.new(method: method,
                          eta: eta,
                          additional_properties: additional_properties)
    end

    def to_custom_eta
      DateTimeHelper.to_rfc3339(eta)
    end

    # Validates an instance of the object from a given value.
    # @param [DeliveryDetails | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} method: #{@method}, eta: #{@eta}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} method: #{@method.inspect}, eta: #{@eta.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
