# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # EmailNotificationCallback Model.
  class EmailNotificationCallback < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :recipient_email

    # TODO: Write general description for this method
    # @return [Status1]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['message_id'] = 'messageId'
      @_hash['recipient_email'] = 'recipientEmail'
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        message_id
        recipient_email
        status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(message_id: SKIP, recipient_email: SKIP, status: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @message_id = message_id unless message_id == SKIP
      @recipient_email = recipient_email unless recipient_email == SKIP
      @status = status unless status == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      message_id = hash.key?('messageId') ? hash['messageId'] : SKIP
      recipient_email =
        hash.key?('recipientEmail') ? hash['recipientEmail'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      EmailNotificationCallback.new(message_id: message_id,
                                    recipient_email: recipient_email,
                                    status: status,
                                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} message_id: #{@message_id}, recipient_email: #{@recipient_email}, status:"\
      " #{@status}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} message_id: #{@message_id.inspect}, recipient_email:"\
      " #{@recipient_email.inspect}, status: #{@status.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
