# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # EventType3.
  class EventType3
    EVENT_TYPE3 = [
      # TODO: Write general description for ENUM_AUDITLOG
      ENUM_AUDITLOG = 'audit.log'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EVENT_TYPE3.include?(value)
    end

    def self.from_value(value, default_value = ENUM_AUDITLOG)
      return default_value if value.nil?

      default_value
    end
  end
end
