# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # EventType1.
  class EventType1
    EVENT_TYPE1 = [
      # TODO: Write general description for ENUM_PAYMENTCOMPLETED
      ENUM_PAYMENTCOMPLETED = 'payment.completed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EVENT_TYPE1.include?(value)
    end

    def self.from_value(value, default_value = ENUM_PAYMENTCOMPLETED)
      return default_value if value.nil?

      default_value
    end
  end
end
