# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # EventType2.
  class EventType2
    EVENT_TYPE2 = [
      # TODO: Write general description for ENUM_PRIMITIVEVARIANT
      ENUM_PRIMITIVEVARIANT = 'primitive.variant'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EVENT_TYPE2.include?(value)
    end

    def self.from_value(value, default_value = ENUM_PRIMITIVEVARIANT)
      return default_value if value.nil?

      default_value
    end
  end
end
