# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # EventType.
  class EventType
    EVENT_TYPE = [
      # TODO: Write general description for ENUM_ORDERUPDATED
      ENUM_ORDERUPDATED = 'order.updated'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EVENT_TYPE.include?(value)
    end

    def self.from_value(value, default_value = ENUM_ORDERUPDATED)
      return default_value if value.nil?

      default_value
    end
  end
end
