# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Event.
  class Event
    EVENT = [
      # TODO: Write general description for ENUM_ORDERCREATED
      ENUM_ORDERCREATED = 'order.created'.freeze,

      # TODO: Write general description for ENUM_ORDERUPDATED
      ENUM_ORDERUPDATED = 'order.updated'.freeze,

      # TODO: Write general description for ENUM_ORDERCANCELLED
      ENUM_ORDERCANCELLED = 'order.cancelled'.freeze,

      # TODO: Write general description for ENUM_PAYMENTCOMPLETED
      ENUM_PAYMENTCOMPLETED = 'payment.completed'.freeze,

      # TODO: Write general description for ENUM_PAYMENTFAILED
      ENUM_PAYMENTFAILED = 'payment.failed'.freeze,

      # TODO: Write general description for ENUM_FULFILLMENTCOMPLETED
      ENUM_FULFILLMENTCOMPLETED = 'fulfillment.completed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EVENT.include?(value)
    end

    def self.from_value(value, default_value = ENUM_ORDERCREATED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enum_ordercreated' then ENUM_ORDERCREATED
      when 'enum_orderupdated' then ENUM_ORDERUPDATED
      when 'enum_ordercancelled' then ENUM_ORDERCANCELLED
      when 'enum_paymentcompleted' then ENUM_PAYMENTCOMPLETED
      when 'enum_paymentfailed' then ENUM_PAYMENTFAILED
      when 'enum_fulfillmentcompleted' then ENUM_FULFILLMENTCOMPLETED
      else
        default_value
      end
    end
  end
end
