# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # FulfillmentStatuss.
  class FulfillmentStatuss
    FULFILLMENT_STATUSS = [
      # TODO: Write general description for FULFILLED
      FULFILLED = 'fulfilled'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for PARTIAL
      PARTIAL = 'partial'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      FULFILLMENT_STATUSS.include?(value)
    end

    def self.from_value(value, default_value = FULFILLED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'fulfilled' then FULFILLED
      when 'failed' then FAILED
      when 'partial' then PARTIAL
      else
        default_value
      end
    end
  end
end
