# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module WebhooksAndCallbacksApi
  # FulfillmentCallback Model.
  class FulfillmentCallback < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :order_id

    # TODO: Write general description for this method
    # @return [FulfillmentStatus]
    attr_accessor :fulfillment_status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :tracking_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :carrier

    # List of scopes that apply to the OAuth token
    # @return [Array[OauthScopeOauthACG]]
    attr_accessor :scopes

    # List of scopes that apply to the OAuth token
    # @return [Date]
    attr_accessor :estimated_delivery

    # List of scopes that apply to the OAuth token
    # @return [DateTime]
    attr_accessor :timestamp

    # Binary file upload
    # @return [Binary]
    attr_accessor :document

    # Binary file upload
    # @return [Float]
    attr_accessor :total_weight

    # Binary file upload
    # @return [Float]
    attr_accessor :price

    # Binary file upload
    # @return [Integer]
    attr_accessor :quantity

    # Binary file upload
    # @return [Integer]
    attr_accessor :long_id

    # Binary file upload
    # @return [TrueClass | FalseClass]
    attr_accessor :fragile

    # Explicitly nullable field
    # @return [String]
    attr_accessor :notes

    # Explicitly nullable field
    # @return [Array[String]]
    attr_accessor :items

    # Explicitly nullable field
    # @return [Array[Package]]
    attr_accessor :packages

    # Explicitly nullable field
    # @return [Address]
    attr_accessor :address

    # Explicitly nullable field
    # @return [Object]
    attr_accessor :metadata

    # Explicitly nullable field
    # @return [Hash[String, String]]
    attr_accessor :attributes

    # Explicitly nullable field
    # @return [Object]
    attr_accessor :delivery_details

    # Explicitly nullable field
    # @return [String]
    attr_accessor :order_idd

    # Explicitly nullable field
    # @return [FulfillmentStatuss]
    attr_accessor :fulfillment_statuss

    # Explicitly nullable field
    # @return [String]
    attr_accessor :tracking_numberr

    # Explicitly nullable field
    # @return [String]
    attr_accessor :carrierr

    # List of scopes that apply to the OAuth token
    # @return [Array[OauthScopeOauthACG]]
    attr_accessor :scopess

    # List of scopes that apply to the OAuth token
    # @return [Date]
    attr_accessor :estimated_deliveryy

    # List of scopes that apply to the OAuth token
    # @return [DateTime]
    attr_accessor :timestampp

    # Binary file upload
    # @return [Binary]
    attr_accessor :documentt

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['order_id'] = 'orderId'
      @_hash['fulfillment_status'] = 'fulfillmentStatus'
      @_hash['tracking_number'] = 'trackingNumber'
      @_hash['carrier'] = 'carrier'
      @_hash['scopes'] = 'scopes'
      @_hash['estimated_delivery'] = 'estimatedDelivery'
      @_hash['timestamp'] = 'timestamp'
      @_hash['document'] = 'document'
      @_hash['total_weight'] = 'totalWeight'
      @_hash['price'] = 'price'
      @_hash['quantity'] = 'quantity'
      @_hash['long_id'] = 'longId'
      @_hash['fragile'] = 'fragile'
      @_hash['notes'] = 'notes'
      @_hash['items'] = 'items'
      @_hash['packages'] = 'packages'
      @_hash['address'] = 'address'
      @_hash['metadata'] = 'metadata'
      @_hash['attributes'] = 'attributes'
      @_hash['delivery_details'] = 'deliveryDetails'
      @_hash['order_idd'] = 'orderIdd'
      @_hash['fulfillment_statuss'] = 'fulfillmentStatuss'
      @_hash['tracking_numberr'] = 'trackingNumberr'
      @_hash['carrierr'] = 'carrierr'
      @_hash['scopess'] = 'scopess'
      @_hash['estimated_deliveryy'] = 'estimatedDeliveryy'
      @_hash['timestampp'] = 'timestampp'
      @_hash['documentt'] = 'documentt'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        tracking_number
        carrier
        scopes
        estimated_delivery
        timestamp
        document
        total_weight
        price
        quantity
        long_id
        fragile
        notes
        items
        packages
        address
        metadata
        attributes
        delivery_details
        order_idd
        fulfillment_statuss
        tracking_numberr
        carrierr
        scopess
        estimated_deliveryy
        timestampp
        documentt
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        order_id
        tracking_number
        scopes
        notes
        order_idd
        tracking_numberr
        scopess
      ]
    end

    def initialize(order_id:, fulfillment_status:, tracking_number: SKIP,
                   carrier: SKIP, scopes: SKIP, estimated_delivery: SKIP,
                   timestamp: SKIP, document: SKIP, total_weight: SKIP,
                   price: SKIP, quantity: SKIP, long_id: SKIP, fragile: SKIP,
                   notes: SKIP, items: SKIP, packages: SKIP, address: SKIP,
                   metadata: SKIP, attributes: SKIP, delivery_details: SKIP,
                   order_idd: SKIP, fulfillment_statuss: SKIP,
                   tracking_numberr: SKIP, carrierr: SKIP, scopess: SKIP,
                   estimated_deliveryy: SKIP, timestampp: SKIP, documentt: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @order_id = order_id
      @fulfillment_status = fulfillment_status
      @tracking_number = tracking_number unless tracking_number == SKIP
      @carrier = carrier unless carrier == SKIP
      @scopes = scopes unless scopes == SKIP
      @estimated_delivery = estimated_delivery unless estimated_delivery == SKIP
      @timestamp = timestamp unless timestamp == SKIP
      @document = document unless document == SKIP
      @total_weight = total_weight unless total_weight == SKIP
      @price = price unless price == SKIP
      @quantity = quantity unless quantity == SKIP
      @long_id = long_id unless long_id == SKIP
      @fragile = fragile unless fragile == SKIP
      @notes = notes unless notes == SKIP
      @items = items unless items == SKIP
      @packages = packages unless packages == SKIP
      @address = address unless address == SKIP
      @metadata = metadata unless metadata == SKIP
      @attributes = attributes unless attributes == SKIP
      @delivery_details = delivery_details unless delivery_details == SKIP
      @order_idd = order_idd unless order_idd == SKIP
      @fulfillment_statuss = fulfillment_statuss unless fulfillment_statuss == SKIP
      @tracking_numberr = tracking_numberr unless tracking_numberr == SKIP
      @carrierr = carrierr unless carrierr == SKIP
      @scopess = scopess unless scopess == SKIP
      @estimated_deliveryy = estimated_deliveryy unless estimated_deliveryy == SKIP
      @timestampp = timestampp unless timestampp == SKIP
      @documentt = documentt unless documentt == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      order_id = hash.key?('orderId') ? hash['orderId'] : nil
      fulfillment_status =
        hash.key?('fulfillmentStatus') ? hash['fulfillmentStatus'] : nil
      tracking_number =
        hash.key?('trackingNumber') ? hash['trackingNumber'] : SKIP
      carrier = hash.key?('carrier') ? hash['carrier'] : SKIP
      scopes = hash.key?('scopes') ? hash['scopes'] : SKIP
      estimated_delivery =
        hash.key?('estimatedDelivery') ? hash['estimatedDelivery'] : SKIP
      timestamp = if hash.key?('timestamp')
                    (DateTimeHelper.from_rfc3339(hash['timestamp']) if hash['timestamp'])
                  else
                    SKIP
                  end
      document = hash.key?('document') ? hash['document'] : SKIP
      total_weight = hash.key?('totalWeight') ? hash['totalWeight'] : SKIP
      price = hash.key?('price') ? hash['price'] : SKIP
      quantity = hash.key?('quantity') ? hash['quantity'] : SKIP
      long_id = hash.key?('longId') ? hash['longId'] : SKIP
      fragile = hash.key?('fragile') ? hash['fragile'] : SKIP
      notes = hash.key?('notes') ? hash['notes'] : SKIP
      items = hash.key?('items') ? hash['items'] : SKIP
      # Parameter is an array, so we need to iterate through it
      packages = nil
      unless hash['packages'].nil?
        packages = []
        hash['packages'].each do |structure|
          packages << (Package.from_hash(structure) if structure)
        end
      end

      packages = SKIP unless hash.key?('packages')
      address = Address.from_hash(hash['address']) if hash['address']
      metadata = hash.key?('metadata') ? hash['metadata'] : SKIP
      attributes = hash.key?('attributes') ? hash['attributes'] : SKIP
      delivery_details = hash.key?('deliveryDetails') ? APIHelper.deserialize_union_type(
        UnionTypeLookUp.get(:FulfillmentCallbackDeliveryDetails), hash['deliveryDetails']
      ) : SKIP
      order_idd = hash.key?('orderIdd') ? hash['orderIdd'] : SKIP
      fulfillment_statuss =
        hash.key?('fulfillmentStatuss') ? hash['fulfillmentStatuss'] : SKIP
      tracking_numberr =
        hash.key?('trackingNumberr') ? hash['trackingNumberr'] : SKIP
      carrierr = hash.key?('carrierr') ? hash['carrierr'] : SKIP
      scopess = hash.key?('scopess') ? hash['scopess'] : SKIP
      estimated_deliveryy =
        hash.key?('estimatedDeliveryy') ? hash['estimatedDeliveryy'] : SKIP
      timestampp = if hash.key?('timestampp')
                     (DateTimeHelper.from_rfc3339(hash['timestampp']) if hash['timestampp'])
                   else
                     SKIP
                   end
      documentt = hash.key?('documentt') ? hash['documentt'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      FulfillmentCallback.new(order_id: order_id,
                              fulfillment_status: fulfillment_status,
                              tracking_number: tracking_number,
                              carrier: carrier,
                              scopes: scopes,
                              estimated_delivery: estimated_delivery,
                              timestamp: timestamp,
                              document: document,
                              total_weight: total_weight,
                              price: price,
                              quantity: quantity,
                              long_id: long_id,
                              fragile: fragile,
                              notes: notes,
                              items: items,
                              packages: packages,
                              address: address,
                              metadata: metadata,
                              attributes: attributes,
                              delivery_details: delivery_details,
                              order_idd: order_idd,
                              fulfillment_statuss: fulfillment_statuss,
                              tracking_numberr: tracking_numberr,
                              carrierr: carrierr,
                              scopess: scopess,
                              estimated_deliveryy: estimated_deliveryy,
                              timestampp: timestampp,
                              documentt: documentt,
                              additional_properties: additional_properties)
    end

    def to_custom_timestamp
      DateTimeHelper.to_rfc3339(timestamp)
    end

    def to_custom_timestampp
      DateTimeHelper.to_rfc3339(timestampp)
    end

    # Validates an instance of the object from a given value.
    # @param [FulfillmentCallback | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.order_id,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.fulfillment_status,
                                  ->(val) { FulfillmentStatus.validate(val) })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['orderId'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['fulfillmentStatus'],
                                ->(val) { FulfillmentStatus.validate(val) })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} order_id: #{@order_id}, fulfillment_status: #{@fulfillment_status},"\
      " tracking_number: #{@tracking_number}, carrier: #{@carrier}, scopes: #{@scopes},"\
      " estimated_delivery: #{@estimated_delivery}, timestamp: #{@timestamp}, document:"\
      " #{@document}, total_weight: #{@total_weight}, price: #{@price}, quantity: #{@quantity},"\
      " long_id: #{@long_id}, fragile: #{@fragile}, notes: #{@notes}, items: #{@items}, packages:"\
      " #{@packages}, address: #{@address}, metadata: #{@metadata}, attributes: #{@attributes},"\
      " delivery_details: #{@delivery_details}, order_idd: #{@order_idd}, fulfillment_statuss:"\
      " #{@fulfillment_statuss}, tracking_numberr: #{@tracking_numberr}, carrierr: #{@carrierr},"\
      " scopess: #{@scopess}, estimated_deliveryy: #{@estimated_deliveryy}, timestampp:"\
      " #{@timestampp}, documentt: #{@documentt}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} order_id: #{@order_id.inspect}, fulfillment_status:"\
      " #{@fulfillment_status.inspect}, tracking_number: #{@tracking_number.inspect}, carrier:"\
      " #{@carrier.inspect}, scopes: #{@scopes.inspect}, estimated_delivery:"\
      " #{@estimated_delivery.inspect}, timestamp: #{@timestamp.inspect}, document:"\
      " #{@document.inspect}, total_weight: #{@total_weight.inspect}, price: #{@price.inspect},"\
      " quantity: #{@quantity.inspect}, long_id: #{@long_id.inspect}, fragile:"\
      " #{@fragile.inspect}, notes: #{@notes.inspect}, items: #{@items.inspect}, packages:"\
      " #{@packages.inspect}, address: #{@address.inspect}, metadata: #{@metadata.inspect},"\
      " attributes: #{@attributes.inspect}, delivery_details: #{@delivery_details.inspect},"\
      " order_idd: #{@order_idd.inspect}, fulfillment_statuss: #{@fulfillment_statuss.inspect},"\
      " tracking_numberr: #{@tracking_numberr.inspect}, carrierr: #{@carrierr.inspect}, scopess:"\
      " #{@scopess.inspect}, estimated_deliveryy: #{@estimated_deliveryy.inspect}, timestampp:"\
      " #{@timestampp.inspect}, documentt: #{@documentt.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
