# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # NotificationCallback Model.
  class NotificationCallback < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :notification_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :subject

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['notification_type'] = 'notificationType'
      @_hash['subject'] = 'subject'
      @_hash['message'] = 'message'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(notification_type:, subject:, message:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @notification_type = notification_type
      @subject = subject
      @message = message
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      notification_type =
        hash.key?('notificationType') ? hash['notificationType'] : nil
      subject = hash.key?('subject') ? hash['subject'] : nil
      message = hash.key?('message') ? hash['message'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      NotificationCallback.new(notification_type: notification_type,
                               subject: subject,
                               message: message,
                               additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [NotificationCallback | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.notification_type,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.subject,
                                  ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.message,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['notificationType'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['subject'],
                                ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['message'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} notification_type: #{@notification_type}, subject: #{@subject}, message:"\
      " #{@message}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} notification_type: #{@notification_type.inspect}, subject:"\
      " #{@subject.inspect}, message: #{@message.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
