# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # OrderItem Model.
  class OrderItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :price

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['product_id'] = 'productId'
      @_hash['quantity'] = 'quantity'
      @_hash['price'] = 'price'
      @_hash['description'] = 'description'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        description
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(product_id:, quantity:, price:, description: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @product_id = product_id
      @quantity = quantity
      @price = price
      @description = description unless description == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      product_id = hash.key?('productId') ? hash['productId'] : nil
      quantity = hash.key?('quantity') ? hash['quantity'] : nil
      price = hash.key?('price') ? hash['price'] : nil
      description = hash.key?('description') ? hash['description'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      OrderItem.new(product_id: product_id,
                    quantity: quantity,
                    price: price,
                    description: description,
                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} product_id: #{@product_id}, quantity: #{@quantity}, price: #{@price},"\
      " description: #{@description}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} product_id: #{@product_id.inspect}, quantity: #{@quantity.inspect}, price:"\
      " #{@price.inspect}, description: #{@description.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
