# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module WebhooksAndCallbacksApi
  # Order Model.
  class Order < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :order_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :customer_id

    # TODO: Write general description for this method
    # @return [Array[OrderItem]]
    attr_accessor :items

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :total_amount

    # TODO: Write general description for this method
    # @return [Status]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :created_at

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :updated_at

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['order_id'] = 'orderId'
      @_hash['customer_id'] = 'customerId'
      @_hash['items'] = 'items'
      @_hash['total_amount'] = 'totalAmount'
      @_hash['status'] = 'status'
      @_hash['created_at'] = 'createdAt'
      @_hash['updated_at'] = 'updatedAt'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        order_id
        customer_id
        items
        total_amount
        status
        created_at
        updated_at
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(order_id: SKIP, customer_id: SKIP, items: SKIP,
                   total_amount: SKIP, status: SKIP, created_at: SKIP,
                   updated_at: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @order_id = order_id unless order_id == SKIP
      @customer_id = customer_id unless customer_id == SKIP
      @items = items unless items == SKIP
      @total_amount = total_amount unless total_amount == SKIP
      @status = status unless status == SKIP
      @created_at = created_at unless created_at == SKIP
      @updated_at = updated_at unless updated_at == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      order_id = hash.key?('orderId') ? hash['orderId'] : SKIP
      customer_id = hash.key?('customerId') ? hash['customerId'] : SKIP
      # Parameter is an array, so we need to iterate through it
      items = nil
      unless hash['items'].nil?
        items = []
        hash['items'].each do |structure|
          items << (OrderItem.from_hash(structure) if structure)
        end
      end

      items = SKIP unless hash.key?('items')
      total_amount = hash.key?('totalAmount') ? hash['totalAmount'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      created_at = if hash.key?('createdAt')
                     (DateTimeHelper.from_rfc3339(hash['createdAt']) if hash['createdAt'])
                   else
                     SKIP
                   end
      updated_at = if hash.key?('updatedAt')
                     (DateTimeHelper.from_rfc3339(hash['updatedAt']) if hash['updatedAt'])
                   else
                     SKIP
                   end

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Order.new(order_id: order_id,
                customer_id: customer_id,
                items: items,
                total_amount: total_amount,
                status: status,
                created_at: created_at,
                updated_at: updated_at,
                additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    def to_custom_updated_at
      DateTimeHelper.to_rfc3339(updated_at)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} order_id: #{@order_id}, customer_id: #{@customer_id}, items: #{@items},"\
      " total_amount: #{@total_amount}, status: #{@status}, created_at: #{@created_at},"\
      " updated_at: #{@updated_at}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} order_id: #{@order_id.inspect}, customer_id: #{@customer_id.inspect},"\
      " items: #{@items.inspect}, total_amount: #{@total_amount.inspect}, status:"\
      " #{@status.inspect}, created_at: #{@created_at.inspect}, updated_at:"\
      " #{@updated_at.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
