# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Package Model.
  class Package < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :package_id

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :weight

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['package_id'] = 'packageId'
      @_hash['weight'] = 'weight'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        package_id
        weight
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(package_id: SKIP, weight: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @package_id = package_id unless package_id == SKIP
      @weight = weight unless weight == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      package_id = hash.key?('packageId') ? hash['packageId'] : SKIP
      weight = hash.key?('weight') ? hash['weight'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Package.new(package_id: package_id,
                  weight: weight,
                  additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Package | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} package_id: #{@package_id}, weight: #{@weight}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} package_id: #{@package_id.inspect}, weight: #{@weight.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
