# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # PaymentStatus.
  class PaymentStatus
    PAYMENT_STATUS = [
      # TODO: Write general description for SUCCESS
      SUCCESS = 'success'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYMENT_STATUS.include?(value)
    end

    def self.from_value(value, default_value = SUCCESS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'success' then SUCCESS
      when 'failed' then FAILED
      when 'pending' then PENDING
      else
        default_value
      end
    end
  end
end
