# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module WebhooksAndCallbacksApi
  # PaymentCallback Model.
  class PaymentCallback < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :order_id

    # TODO: Write general description for this method
    # @return [PaymentStatus]
    attr_accessor :payment_status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :transaction_id

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :amount

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :currency

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :timestamp

    # Reason for payment failure (if applicable)
    # @return [String]
    attr_accessor :failure_reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['order_id'] = 'orderId'
      @_hash['payment_status'] = 'paymentStatus'
      @_hash['transaction_id'] = 'transactionId'
      @_hash['amount'] = 'amount'
      @_hash['currency'] = 'currency'
      @_hash['timestamp'] = 'timestamp'
      @_hash['failure_reason'] = 'failureReason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        amount
        currency
        timestamp
        failure_reason
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(order_id:, payment_status:, transaction_id:, amount: SKIP,
                   currency: SKIP, timestamp: SKIP, failure_reason: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @order_id = order_id
      @payment_status = payment_status
      @transaction_id = transaction_id
      @amount = amount unless amount == SKIP
      @currency = currency unless currency == SKIP
      @timestamp = timestamp unless timestamp == SKIP
      @failure_reason = failure_reason unless failure_reason == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      order_id = hash.key?('orderId') ? hash['orderId'] : nil
      payment_status = hash.key?('paymentStatus') ? hash['paymentStatus'] : nil
      transaction_id = hash.key?('transactionId') ? hash['transactionId'] : nil
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      currency = hash.key?('currency') ? hash['currency'] : SKIP
      timestamp = if hash.key?('timestamp')
                    (DateTimeHelper.from_rfc3339(hash['timestamp']) if hash['timestamp'])
                  else
                    SKIP
                  end
      failure_reason = hash.key?('failureReason') ? hash['failureReason'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PaymentCallback.new(order_id: order_id,
                          payment_status: payment_status,
                          transaction_id: transaction_id,
                          amount: amount,
                          currency: currency,
                          timestamp: timestamp,
                          failure_reason: failure_reason,
                          additional_properties: additional_properties)
    end

    def to_custom_timestamp
      DateTimeHelper.to_rfc3339(timestamp)
    end

    # Validates an instance of the object from a given value.
    # @param [PaymentCallback | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return (
          APIHelper.valid_type?(value.order_id,
                                ->(val) { val.instance_of? String }) and
            APIHelper.valid_type?(value.payment_status,
                                  ->(val) { PaymentStatus.validate(val) }) and
            APIHelper.valid_type?(value.transaction_id,
                                  ->(val) { val.instance_of? String })
        )
      end

      return false unless value.instance_of? Hash

      (
        APIHelper.valid_type?(value['orderId'],
                              ->(val) { val.instance_of? String }) and
          APIHelper.valid_type?(value['paymentStatus'],
                                ->(val) { PaymentStatus.validate(val) }) and
          APIHelper.valid_type?(value['transactionId'],
                                ->(val) { val.instance_of? String })
      )
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} order_id: #{@order_id}, payment_status: #{@payment_status}, transaction_id:"\
      " #{@transaction_id}, amount: #{@amount}, currency: #{@currency}, timestamp: #{@timestamp},"\
      " failure_reason: #{@failure_reason}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} order_id: #{@order_id.inspect}, payment_status: #{@payment_status.inspect},"\
      " transaction_id: #{@transaction_id.inspect}, amount: #{@amount.inspect}, currency:"\
      " #{@currency.inspect}, timestamp: #{@timestamp.inspect}, failure_reason:"\
      " #{@failure_reason.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
