# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # PrimitiveCollectionEvent Model.
  class PrimitiveCollectionEvent < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [EventType2]
    attr_accessor :event_type

    # TODO: Write general description for this method
    # @return [Array[Integer]]
    attr_accessor :ids

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['event_type'] = 'eventType'
      @_hash['ids'] = 'ids'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        event_type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(ids:, event_type: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @event_type = event_type unless event_type == SKIP
      @ids = ids
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ids = hash.key?('ids') ? hash['ids'] : nil
      event_type = hash.key?('eventType') ? hash['eventType'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PrimitiveCollectionEvent.new(ids: ids,
                                   event_type: event_type,
                                   additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [PrimitiveCollectionEvent | Hash] The value against the validation is performed.
    def self.validate(value)
      if value.instance_of? self
        return APIHelper.valid_type?(value.ids,
                                     ->(val) { val.instance_of? Integer })
      end

      return false unless value.instance_of? Hash

      APIHelper.valid_type?(value['ids'],
                            ->(val) { val.instance_of? Integer })
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} event_type: #{@event_type}, ids: #{@ids}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} event_type: #{@event_type.inspect}, ids: #{@ids.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
