# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # RootLevelPrimitiveOneOfEvent Request.
  class RootLevelPrimitiveOneOfEventRequest
    ROOT_LEVEL_PRIMITIVE_ONE_OF_EVENT_REQUEST = [
      # TODO: Write general description for ON
      ON = 'on'.freeze,

      # TODO: Write general description for OFF
      OFF = 'off'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ROOT_LEVEL_PRIMITIVE_ONE_OF_EVENT_REQUEST.include?(value)
    end

    def self.from_value(value, default_value = ON)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'on' then ON
      when 'off' then OFF
      when 'pending' then PENDING
      else
        default_value
      end
    end
  end
end
