# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # RootLevelPrimitiveOneOfEvent Request1.
  class RootLevelPrimitiveOneOfEventRequest1
    ROOT_LEVEL_PRIMITIVE_ONE_OF_EVENT_REQUEST1 = [
      # TODO: Write general description for ALPHA
      ALPHA = 'alpha'.freeze,

      # TODO: Write general description for BETA
      BETA = 'beta'.freeze,

      # TODO: Write general description for GAMMA
      GAMMA = 'gamma'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ROOT_LEVEL_PRIMITIVE_ONE_OF_EVENT_REQUEST1.include?(value)
    end

    def self.from_value(value, default_value = ALPHA)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'alpha' then ALPHA
      when 'beta' then BETA
      when 'gamma' then GAMMA
      else
        default_value
      end
    end
  end
end
