# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Status.
  class Status
    STATUS = [
      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze,

      # TODO: Write general description for PROCESSING
      PROCESSING = 'processing'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'completed'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'cancelled'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS.include?(value)
    end

    def self.from_value(value, default_value = PENDING)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'pending' then PENDING
      when 'processing' then PROCESSING
      when 'completed' then COMPLETED
      when 'cancelled' then CANCELLED
      else
        default_value
      end
    end
  end
end
