# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Status1.
  class Status1
    STATUS1 = [
      # TODO: Write general description for SENT
      SENT = 'sent'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS1.include?(value)
    end

    def self.from_value(value, default_value = SENT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'sent' then SENT
      when 'failed' then FAILED
      else
        default_value
      end
    end
  end
end
