# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Status2.
  class Status2
    STATUS2 = [
      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS2.include?(value)
    end

    def self.from_value(value, default_value = DELIVERED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'delivered' then DELIVERED
      when 'failed' then FAILED
      else
        default_value
      end
    end
  end
end
