# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # WebhookRegistration Model.
  class WebhookRegistration < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The endpoint URL that will receive webhook events
    # @return [String]
    attr_accessor :url

    # List of events to subscribe to
    # @return [Array[Event]]
    attr_accessor :events

    # Secret key for webhook signature verification
    # @return [String]
    attr_accessor :secret

    # Whether the webhook is active
    # @return [TrueClass | FalseClass]
    attr_accessor :active

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['url'] = 'url'
      @_hash['events'] = 'events'
      @_hash['secret'] = 'secret'
      @_hash['active'] = 'active'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        secret
        active
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(url:, events:, secret: SKIP, active: true,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @url = url
      @events = events
      @secret = secret unless secret == SKIP
      @active = active unless active == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      url = hash.key?('url') ? hash['url'] : nil
      events = hash.key?('events') ? hash['events'] : nil
      secret = hash.key?('secret') ? hash['secret'] : SKIP
      active = hash['active'] ||= true

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WebhookRegistration.new(url: url,
                              events: events,
                              secret: secret,
                              active: active,
                              additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} url: #{@url}, events: #{@events}, secret: #{@secret}, active: #{@active},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} url: #{@url.inspect}, events: #{@events.inspect}, secret:"\
      " #{@secret.inspect}, active: #{@active.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
