# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module WebhooksAndCallbacksApi
  # Webhook Model.
  class Webhook < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :webhook_id

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :created_at

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :updated_at

    # Timestamp of the last successful delivery
    # @return [DateTime]
    attr_accessor :last_delivery

    # Total number of events delivered
    # @return [Integer]
    attr_accessor :delivery_count

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['webhook_id'] = 'webhookId'
      @_hash['created_at'] = 'createdAt'
      @_hash['updated_at'] = 'updatedAt'
      @_hash['last_delivery'] = 'lastDelivery'
      @_hash['delivery_count'] = 'deliveryCount'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        webhook_id
        created_at
        updated_at
        last_delivery
        delivery_count
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(webhook_id: SKIP, created_at: SKIP, updated_at: SKIP,
                   last_delivery: SKIP, delivery_count: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @webhook_id = webhook_id unless webhook_id == SKIP
      @created_at = created_at unless created_at == SKIP
      @updated_at = updated_at unless updated_at == SKIP
      @last_delivery = last_delivery unless last_delivery == SKIP
      @delivery_count = delivery_count unless delivery_count == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      webhook_id = hash.key?('webhookId') ? hash['webhookId'] : SKIP
      created_at = if hash.key?('createdAt')
                     (DateTimeHelper.from_rfc3339(hash['createdAt']) if hash['createdAt'])
                   else
                     SKIP
                   end
      updated_at = if hash.key?('updatedAt')
                     (DateTimeHelper.from_rfc3339(hash['updatedAt']) if hash['updatedAt'])
                   else
                     SKIP
                   end
      last_delivery = if hash.key?('lastDelivery')
                        (DateTimeHelper.from_rfc3339(hash['lastDelivery']) if hash['lastDelivery'])
                      else
                        SKIP
                      end
      delivery_count = hash.key?('deliveryCount') ? hash['deliveryCount'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Webhook.new(webhook_id: webhook_id,
                  created_at: created_at,
                  updated_at: updated_at,
                  last_delivery: last_delivery,
                  delivery_count: delivery_count,
                  additional_properties: additional_properties)
    end

    def to_custom_created_at
      DateTimeHelper.to_rfc3339(created_at)
    end

    def to_custom_updated_at
      DateTimeHelper.to_rfc3339(updated_at)
    end

    def to_custom_last_delivery
      DateTimeHelper.to_rfc3339(last_delivery)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} webhook_id: #{@webhook_id}, created_at: #{@created_at}, updated_at:"\
      " #{@updated_at}, last_delivery: #{@last_delivery}, delivery_count: #{@delivery_count},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} webhook_id: #{@webhook_id.inspect}, created_at: #{@created_at.inspect},"\
      " updated_at: #{@updated_at.inspect}, last_delivery: #{@last_delivery.inspect},"\
      " delivery_count: #{@delivery_count.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
