# cypress_test_api
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module CypressTestApi
  # Represents a single Http Request.
  class HttpRequest < CoreLibrary::HttpRequest
  end
end
