# cypress_test_api
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module CypressTestApi
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
