# cypress_test_api
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module CypressTestApi
  ##
  # ProxySettings encapsulates HTTP proxy configuration for Faraday,
  # including optional basic authentication.
  #
  class ProxySettings < CoreLibrary::ProxySettings
  end
end
