# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Utility class for custom header authorization.
  class ApiKey < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'ApiKey: x_api_key is undefined.'
    end

    # Initialization constructor.
    def initialize(api_key_credentials)
      auth_params = {}
      auth_params['X-API-Key'] = api_key_credentials.x_api_key unless
        api_key_credentials.nil? || api_key_credentials.x_api_key.nil?

      super auth_params
    end
  end

  # Data class for ApiKeyCredentials.
  # Data class for ApiKeyCredentials.
  class ApiKeyCredentials
    attr_reader :x_api_key

    def initialize(x_api_key:)
      raise ArgumentError, 'x_api_key cannot be nil' if x_api_key.nil?

      @x_api_key = x_api_key
    end

    def self.from_env
      x_api_key = ENV['API_KEY_X_API_KEY']
      all_nil = [
        x_api_key
      ].all?(&:nil?)
      return nil if all_nil

      new(x_api_key: x_api_key)
    end

    def clone_with(x_api_key: nil)
      x_api_key ||= self.x_api_key

      ApiKeyCredentials.new(x_api_key: x_api_key)
    end
  end
end
