# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'nokogiri'

module SwaggerPetstoreOpenApi30
  # A utility class for handling xml parsing.
  class XmlUtilities < CoreLibrary::XmlHelper
  end
end
