# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # Error class.
  class ErrorException < APIException
    SKIP = Object.new
    private_constant :SKIP

    # Error code
    # @return [String]
    attr_accessor :error

    # Human-readable error message
    # @return [String]
    attr_accessor :message

    # Additional error details
    # @return [Object]
    attr_accessor :details

    # The constructor.
    # @param [String] reason The reason for raising an exception.
    # @param [HttpResponse] response The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] hash The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      return nil unless hash

      @error = hash.key?('error') ? hash['error'] : nil
      @message = hash.key?('message') ? hash['message'] : nil
      @details = hash.key?('details') ? hash['details'] : SKIP
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} error: #{@error}, message: #{@message}, details: #{@details}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} error: #{@error.inspect}, message: #{@message.inspect}, details:"\
      " #{@details.inspect}>"
    end
  end
end
