# swagger_petstore
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'swagger_petstore'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include SwaggerPetstore
  include CoreLibrary

  # Initializes the base test controller
  def setup_class
    @client = Client.from_env(
      http_basic_credentials: HttpBasicCredentials.new(username: 'test',
                                                       passwprd: 'testPassword'),
      http_callback: HttpResponseCatcher.new
    )

    _config = @client.config
    petstore_auth_token = @client.petstore_auth.fetch_token()
    petstore_auth_credentials = _config.petstore_auth_credentials.clone_with(o_auth_token: petstore_auth_token)
    _config = _config.clone_with(petstore_auth_credentials: petstore_auth_credentials)
    @client = Client.new(config: _config)  end
end
