# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # PetApi
  class PetApi < BaseApi
    # Update an existing pet by Id.
    # @param [String] name Required parameter: TODO: type description here
    # @param [Array[String]] photo_urls Required parameter: TODO: type
    # description here
    # @param [Integer] id Optional parameter: TODO: type description here
    # @param [Category] category Optional parameter: TODO: type description
    # here
    # @param [Array[Tag]] tags Optional parameter: TODO: type description here
    # @param [PetStatus] status Optional parameter: pet status in the store
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_pet(name,
                   photo_urls,
                   id: nil,
                   category: nil,
                   tags: nil,
                   status: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::PUT,
                                     '/pet',
                                     Server::DEFAULT)
                   .form_param(new_parameter(name, key: 'name')
                                .is_required(true))
                   .form_param(new_parameter(photo_urls, key: 'photoUrls')
                                .is_required(true))
                   .form_param(new_parameter(id, key: 'id'))
                   .form_param(new_parameter(category, key: 'category'))
                   .form_param(new_parameter(tags, key: 'tags'))
                   .form_param(new_parameter(status, key: 'status'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('petstore_auth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Pet.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid ID supplied',
                                 APIException)
                    .local_error('404',
                                 'Pet not found',
                                 APIException)
                    .local_error('422',
                                 'Validation exception',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Add a new pet to the store.
    # @param [String] name Required parameter: TODO: type description here
    # @param [Array[String]] photo_urls Required parameter: TODO: type
    # description here
    # @param [Integer] id Optional parameter: TODO: type description here
    # @param [Category] category Optional parameter: TODO: type description
    # here
    # @param [Array[Tag]] tags Optional parameter: TODO: type description here
    # @param [PetStatus] status Optional parameter: pet status in the store
    # @return [ApiResponse] Complete http response with raw body and status code.
    def add_pet(name,
                photo_urls,
                id: nil,
                category: nil,
                tags: nil,
                status: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/pet',
                                     Server::DEFAULT)
                   .form_param(new_parameter(name, key: 'name')
                                .is_required(true))
                   .form_param(new_parameter(photo_urls, key: 'photoUrls')
                                .is_required(true))
                   .form_param(new_parameter(id, key: 'id'))
                   .form_param(new_parameter(category, key: 'category'))
                   .form_param(new_parameter(tags, key: 'tags'))
                   .form_param(new_parameter(status, key: 'status'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('petstore_auth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Pet.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid input',
                                 APIException)
                    .local_error('422',
                                 'Validation exception',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Multiple status values can be provided with comma separated strings.
    # @param [PetStatus] status Optional parameter: Status values that need to
    # be considered for filter
    # @return [ApiResponse] Complete http response with raw body and status code.
    def find_pets_by_status(status: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/pet/findByStatus',
                                     Server::DEFAULT)
                   .query_param(new_parameter(status, key: 'status'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('petstore_auth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Pet.method(:from_hash))
                    .is_api_response(true)
                    .is_response_array(true)
                    .local_error('400',
                                 'Invalid status value',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Multiple tags can be provided with comma separated strings. Use tag1,
    # tag2, tag3 for testing.
    # @param [Array[String]] tags Optional parameter: Tags to filter by
    # @return [ApiResponse] Complete http response with raw body and status code.
    def find_pets_by_tags(tags: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/pet/findByTags',
                                     Server::DEFAULT)
                   .query_param(new_parameter(tags, key: 'tags'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('petstore_auth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Pet.method(:from_hash))
                    .is_api_response(true)
                    .is_response_array(true)
                    .local_error('400',
                                 'Invalid tag value',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Returns a single pet.
    # @param [Integer] pet_id Required parameter: ID of pet to return
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_pet_by_id(pet_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/pet/{petId}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(pet_id, key: 'petId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Or.new('api_key', 'petstore_auth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Pet.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid ID supplied',
                                 APIException)
                    .local_error('404',
                                 'Pet not found',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Updates a pet resource based on the form data.
    # @param [Integer] pet_id Required parameter: ID of pet that needs to be
    # updated
    # @param [String] name Optional parameter: Name of pet that needs to be
    # updated
    # @param [String] status Optional parameter: Status of pet that needs to be
    # updated
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_pet_with_form(pet_id,
                             name: nil,
                             status: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/pet/{petId}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(pet_id, key: 'petId')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(name, key: 'name'))
                   .query_param(new_parameter(status, key: 'status'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('petstore_auth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Pet.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid input',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Delete a pet.
    # @param [Integer] pet_id Required parameter: Pet id to delete
    # @param [String] api_key Optional parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_pet(pet_id,
                   api_key: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/pet/{petId}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(pet_id, key: 'petId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(api_key, key: 'api_key'))
                   .auth(Single.new('petstore_auth')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid pet value',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Upload image of the pet.
    # @param [Integer] pet_id Required parameter: ID of pet to update
    # @param [String] additional_metadata Optional parameter: Additional
    # Metadata
    # @param [File | UploadIO] body Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def upload_file(pet_id,
                    additional_metadata: nil,
                    body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/pet/{petId}/uploadImage',
                                     Server::DEFAULT)
                   .template_param(new_parameter(pet_id, key: 'petId')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(additional_metadata, key: 'additionalMetadata'))
                   .multipart_param(new_parameter(body, key: 'body')
                                     .default_content_type('application/octet-stream'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('petstore_auth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ApiResponse.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'No file uploaded',
                                 APIException)
                    .local_error('404',
                                 'Pet not found',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end
  end
end
