# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # StoreApi
  class StoreApi < BaseApi
    # Returns a map of status codes to quantities.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_inventory
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/store/inventory',
                                     Server::DEFAULT)
                   .auth(Single.new('api_key')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:deserialize_primitive_types))
                    .deserialize_into(proc do |response| response&.to_i end)
                    .is_api_response(true)
                    .is_primitive_response(true)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Place a new order in the store.
    # @param [Integer] id Optional parameter: TODO: type description here
    # @param [Integer] pet_id Optional parameter: TODO: type description here
    # @param [Integer] quantity Optional parameter: TODO: type description
    # here
    # @param [DateTime] ship_date Optional parameter: TODO: type description
    # here
    # @param [OrderStatus] status Optional parameter: Order Status
    # @param [TrueClass | FalseClass] complete Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def place_order(id: nil,
                    pet_id: nil,
                    quantity: nil,
                    ship_date: nil,
                    status: nil,
                    complete: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/store/order',
                                     Server::DEFAULT)
                   .form_param(new_parameter(id, key: 'id'))
                   .form_param(new_parameter(pet_id, key: 'petId'))
                   .form_param(new_parameter(quantity, key: 'quantity'))
                   .form_param(new_parameter(ship_date, key: 'shipDate'))
                   .form_param(new_parameter(status, key: 'status'))
                   .form_param(new_parameter(complete, key: 'complete'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Order.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid input',
                                 APIException)
                    .local_error('422',
                                 'Validation exception',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # For valid response try integer IDs with value <= 5 or > 10. Other values
    # will generate exceptions.
    # @param [Integer] order_id Required parameter: ID of order that needs to be
    # fetched
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_order_by_id(order_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/store/order/{orderId}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(order_id, key: 'orderId')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Order.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid ID supplied',
                                 APIException)
                    .local_error('404',
                                 'Order not found',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # For valid response try integer IDs with value < 1000. Anything above 1000
    # or non-integers will generate API errors.
    # @param [Integer] order_id Required parameter: ID of the order that needs
    # to be deleted
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_order(order_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/store/order/{orderId}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(order_id, key: 'orderId')
                                    .is_required(true)
                                    .should_encode(true)))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid ID supplied',
                                 APIException)
                    .local_error('404',
                                 'Order not found',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end
  end
end
