# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # UserApi
  class UserApi < BaseApi
    # This can only be done by the logged in user.
    # @param [Integer] id Optional parameter: TODO: type description here
    # @param [String] username Optional parameter: TODO: type description here
    # @param [String] first_name Optional parameter: TODO: type description
    # here
    # @param [String] last_name Optional parameter: TODO: type description
    # here
    # @param [String] email Optional parameter: TODO: type description here
    # @param [String] password Optional parameter: TODO: type description here
    # @param [String] phone Optional parameter: TODO: type description here
    # @param [Integer] user_status Optional parameter: User Status
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_user(id: nil,
                    username: nil,
                    first_name: nil,
                    last_name: nil,
                    email: nil,
                    password: nil,
                    phone: nil,
                    user_status: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/user',
                                     Server::DEFAULT)
                   .form_param(new_parameter(id, key: 'id'))
                   .form_param(new_parameter(username, key: 'username'))
                   .form_param(new_parameter(first_name, key: 'firstName'))
                   .form_param(new_parameter(last_name, key: 'lastName'))
                   .form_param(new_parameter(email, key: 'email'))
                   .form_param(new_parameter(password, key: 'password'))
                   .form_param(new_parameter(phone, key: 'phone'))
                   .form_param(new_parameter(user_status, key: 'userStatus'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(User.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Creates list of users with given input array.
    # @param [Array[User]] body Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_users_with_list_input(body: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/user/createWithList',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(User.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Log into the system.
    # @param [String] username Optional parameter: The user name for login
    # @param [String] password Optional parameter: The password for login in
    # clear text
    # @return [ApiResponse] Complete http response with raw body and status code.
    def login_user(username: nil,
                   password: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/user/login',
                                     Server::DEFAULT)
                   .query_param(new_parameter(username, key: 'username'))
                   .query_param(new_parameter(password, key: 'password'))
                   .header_param(new_parameter('application/xml', key: 'accept')))
        .response(new_response_handler
                    .deserializer(XmlUtilities.method(:deserialize_xml))
                    .deserialize_into(String)
                    .is_xml_response(true)
                    .xml_attribute(XmlAttributes.new
                                                .root_element_name('response'))
                    .is_api_response(true)
                    .is_primitive_response(true)
                    .local_error('400',
                                 'Invalid username/password supplied',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Log user out of the system.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def logout_user
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/user/logout',
                                     Server::DEFAULT))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # Get user detail based on username.
    # @param [String] usersname Required parameter: The username that needs to
    # be processed
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_user_by_name(usersname)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/user/{usersname}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(usersname, key: 'usersname')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(User.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid username supplied',
                                 APIException)
                    .local_error('404',
                                 'User not found',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # This can only be done by the logged in user.
    # @param [String] usersname Required parameter: The username that needs to
    # be processed
    # @param [Integer] id Optional parameter: TODO: type description here
    # @param [String] username Optional parameter: TODO: type description here
    # @param [String] first_name Optional parameter: TODO: type description
    # here
    # @param [String] last_name Optional parameter: TODO: type description
    # here
    # @param [String] email Optional parameter: TODO: type description here
    # @param [String] password Optional parameter: TODO: type description here
    # @param [String] phone Optional parameter: TODO: type description here
    # @param [Integer] user_status Optional parameter: User Status
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_user(usersname,
                    id: nil,
                    username: nil,
                    first_name: nil,
                    last_name: nil,
                    email: nil,
                    password: nil,
                    phone: nil,
                    user_status: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::PUT,
                                     '/user/{usersname}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(usersname, key: 'usersname')
                                    .is_required(true)
                                    .should_encode(true))
                   .form_param(new_parameter(id, key: 'id'))
                   .form_param(new_parameter(username, key: 'username'))
                   .form_param(new_parameter(first_name, key: 'firstName'))
                   .form_param(new_parameter(last_name, key: 'lastName'))
                   .form_param(new_parameter(email, key: 'email'))
                   .form_param(new_parameter(password, key: 'password'))
                   .form_param(new_parameter(phone, key: 'phone'))
                   .form_param(new_parameter(user_status, key: 'userStatus'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'bad request',
                                 APIException)
                    .local_error('404',
                                 'user not found',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end

    # This can only be done by the logged in user.
    # @param [String] usersname Required parameter: The username that needs to
    # be processed
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_user(usersname)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/user/{usersname}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(usersname, key: 'usersname')
                                    .is_required(true)
                                    .should_encode(true)))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid username supplied',
                                 APIException)
                    .local_error('404',
                                 'User not found',
                                 APIException)
                    .local_error('default',
                                 'Unexpected error',
                                 APIException))
        .execute
    end
  end
end
