# swagger_petstore
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module SwaggerPetstore
  # An enum for SDK environments.
  class Environment
    ENVIRONMENT = [
      PRODUCTION = 'production'.freeze,
      ENVIRONMENT2 = 'environment2'.freeze,
      ENVIRONMENT3 = 'environment3'.freeze
    ].freeze

    # Converts a string or symbol into a valid Environment constant.
    def self.from_value(value, default_value = PRODUCTION)
      return default_value if value.nil?

      str = value.to_s.strip.downcase
      case str
      when 'production' then PRODUCTION
      when 'environment2' then ENVIRONMENT2
      when 'environment3' then ENVIRONMENT3

      else
        warn "[Environment] Unknown environment '#{value}', falling back to #{default_value} "
        default_value
      end
    end
  end

  # An enum for API servers.
  class Server
    SERVER = [
      DEFAULT = 'default'.freeze
    ].freeze

    # Converts a string or symbol into a valid Server constant.
    def self.from_value(value, default_value = DEFAULT)
      return default_value if value.nil?

      default_value
    end
  end

  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration < CoreLibrary::HttpClientConfiguration
    # The attribute readers for properties.
    attr_reader :environment, :api_key_credentials, :http_basic_credentials,
                :petstore_auth_credentials, :test_header

    class << self
      attr_reader :environments
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 60,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put], http_callback: nil, proxy_settings: nil,
      environment: Environment::PRODUCTION, api_key_credentials: nil,
      http_basic_credentials: nil, petstore_auth_credentials: nil,
      test_header: 'TestHeaderDefaultValue'
    )
      super connection: connection, adapter: adapter, timeout: timeout,
            max_retries: max_retries, retry_interval: retry_interval,
            backoff_factor: backoff_factor, retry_statuses: retry_statuses,
            retry_methods: retry_methods, http_callback: http_callback,
            proxy_settings: proxy_settings

      # Current API environment
      @environment = String(environment)

      # The object holding Custom Header Signature credentials
      @api_key_credentials = api_key_credentials

      # The object holding Basic Authentication credentials
      @http_basic_credentials = http_basic_credentials

      # The object holding OAuth 2 Implicit Grant credentials
      @petstore_auth_credentials = petstore_auth_credentials

      # This is a test header
      @test_header = test_header

      # The Http Client to use for making requests.
      set_http_client CoreLibrary::FaradayClient.new(self)
    end

    def clone_with(connection: nil, adapter: nil, timeout: nil,
                   max_retries: nil, retry_interval: nil, backoff_factor: nil,
                   retry_statuses: nil, retry_methods: nil, http_callback: nil,
                   proxy_settings: nil, environment: nil,
                   api_key_credentials: nil, http_basic_credentials: nil,
                   petstore_auth_credentials: nil, test_header: nil)
      connection ||= self.connection
      adapter ||= self.adapter
      timeout ||= self.timeout
      max_retries ||= self.max_retries
      retry_interval ||= self.retry_interval
      backoff_factor ||= self.backoff_factor
      retry_statuses ||= self.retry_statuses
      retry_methods ||= self.retry_methods
      http_callback ||= self.http_callback
      proxy_settings ||= self.proxy_settings
      environment ||= self.environment
      api_key_credentials ||= self.api_key_credentials
      http_basic_credentials ||= self.http_basic_credentials
      petstore_auth_credentials ||= self.petstore_auth_credentials
      test_header ||= self.test_header

      Configuration.new(connection: connection, adapter: adapter,
                        timeout: timeout, max_retries: max_retries,
                        retry_interval: retry_interval,
                        backoff_factor: backoff_factor,
                        retry_statuses: retry_statuses,
                        retry_methods: retry_methods,
                        http_callback: http_callback,
                        proxy_settings: proxy_settings,
                        environment: environment,
                        api_key_credentials: api_key_credentials,
                        http_basic_credentials: http_basic_credentials,
                        petstore_auth_credentials: petstore_auth_credentials,
                        test_header: test_header)
    end


    # All the environments the SDK can run in.
    ENVIRONMENTS = {
      Environment::PRODUCTION => {
        Server::DEFAULT => 'https://petstore.swagger.io/v2'
      },
      Environment::ENVIRONMENT2 => {
        Server::DEFAULT => 'http://petstore.swagger.io/v2'
      },
      Environment::ENVIRONMENT3 => {
        Server::DEFAULT => 'https://petstore.swagger.io/oauth'
      }
    }.freeze

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] server The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def get_base_uri(server = Server::DEFAULT)
      ENVIRONMENTS[environment][server].clone
    end

    # Builds a Configuration instance using environment variables.
    def self.build_default_config_from_env
      # === Core environment ===
      environment = Environment.from_value(ENV.fetch('ENVIRONMENT', 'production'))
      test_header = ENV.fetch('TEST_HEADER', 'TestHeaderDefaultValue')
      timeout = (ENV['TIMEOUT'] || 60).to_f
      max_retries = (ENV['MAX_RETRIES'] || 0).to_i
      retry_interval = (ENV['RETRY_INTERVAL'] || 1).to_f
      backoff_factor = (ENV['BACKOFF_FACTOR'] || 2).to_f
      retry_statuses = ENV.fetch('RETRY_STATUSES',
                                 '[408, 413, 429, 500, 502, 503, 504, 521, 522, 524]').gsub(/[\[\]]/, '')
                                          .split(',')
                                          .map(&:strip)
                                          .map do |item|
                                            item.match?(/\A\d+\z/) ? item.to_i : item.downcase
                                          end
      retry_methods = ENV.fetch('RETRY_METHODS', '%i[get put]').gsub(/[\[\]]/, '')
                                          .split(',')
                                          .map(&:strip)
                                          .map do |item|
                                            item.match?(/\A\d+\z/) ? item.to_i : item.downcase
                                          end

      # === Authentication credentials ===
      api_key_credentials = ApiKeyCredentials.from_env
      http_basic_credentials = HttpBasicCredentials.from_env
      petstore_auth_credentials = PetstoreAuthCredentials.from_env

      # === Proxy settings ===
      proxy_settings = ProxySettings.from_env

      Configuration.new(
        environment: environment,
        test_header: test_header,
        timeout: timeout,
        max_retries: max_retries,
        retry_interval: retry_interval,
        backoff_factor: backoff_factor,
        retry_statuses: retry_statuses,
        retry_methods: retry_methods,
        api_key_credentials: api_key_credentials,
        http_basic_credentials: http_basic_credentials,
        petstore_auth_credentials: petstore_auth_credentials,
        proxy_settings: proxy_settings
      )
    end
  end
end
