# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # ApiResponse Model.
  class ApiResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'code'
      @_hash['type'] = 'type'
      @_hash['message'] = 'message'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        code
        type
        message
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(code: SKIP, type: SKIP, message: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @code = code unless code == SKIP
      @type = type unless type == SKIP
      @message = message unless message == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash.key?('code') ? hash['code'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      message = hash.key?('message') ? hash['message'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ApiResponse.new(code: code,
                      type: type,
                      message: message,
                      additional_properties: additional_properties)
    end

    def self.from_element(root)
      code = XmlUtilities.from_element(root, 'code', Integer)
      type = XmlUtilities.from_element(root, 'type', String)
      message = XmlUtilities.from_element(root, 'message', String)

      new(code: code,
          type: type,
          message: message,
          additional_properties: additional_properties)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'code', code)
      XmlUtilities.add_as_subelement(doc, root, 'type', type)
      XmlUtilities.add_as_subelement(doc, root, 'message', message)
      XmlUtilities.add_as_subelement(doc, root, 'additional_properties',
                                     additional_properties)

      root
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} code: #{@code}, type: #{@type}, message: #{@message},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} code: #{@code.inspect}, type: #{@type.inspect}, message:"\
      " #{@message.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
