# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # OAuth 2 scopes supported by the API
  class OauthScopePetstoreAuth
    OAUTH_SCOPE_PETSTORE_AUTH = [
      # modify pets in your account
      WRITEPETS = 'write:pets'.freeze,

      # read your pets
      READPETS = 'read:pets'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      OAUTH_SCOPE_PETSTORE_AUTH.include?(value)
    end

    def self.from_value(value, default_value = WRITEPETS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'writepets' then WRITEPETS
      when 'readpets' then READPETS
      else
        default_value
      end
    end
  end
end
