# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # OAuth 2 Authorization endpoint response
  class OauthToken < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Access token
    # @return [String]
    attr_accessor :access_token

    # Type of access token
    # @return [String]
    attr_accessor :token_type

    # Time in seconds before the access token expires
    # @return [Integer]
    attr_accessor :expires_in

    # List of scopes granted
    # This is a space-delimited list of strings.
    # @return [String]
    attr_accessor :scope

    # Time of token expiry as unix timestamp (UTC)
    # @return [Integer]
    attr_accessor :expiry

    # Refresh token
    # Used to get a new access token when it expires.
    # @return [String]
    attr_accessor :refresh_token

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['access_token'] = 'access_token'
      @_hash['token_type'] = 'token_type'
      @_hash['expires_in'] = 'expires_in'
      @_hash['scope'] = 'scope'
      @_hash['expiry'] = 'expiry'
      @_hash['refresh_token'] = 'refresh_token'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        expires_in
        scope
        expiry
        refresh_token
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(access_token:, token_type:, expires_in: SKIP, scope: SKIP,
                   expiry: SKIP, refresh_token: SKIP)
      @access_token = access_token
      @token_type = token_type
      @expires_in = expires_in unless expires_in == SKIP
      @scope = scope unless scope == SKIP
      @expiry = expiry unless expiry == SKIP
      @refresh_token = refresh_token unless refresh_token == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      access_token = hash.key?('access_token') ? hash['access_token'] : nil
      token_type = hash.key?('token_type') ? hash['token_type'] : nil
      expires_in = hash.key?('expires_in') ? hash['expires_in'] : SKIP
      scope = hash.key?('scope') ? hash['scope'] : SKIP
      expiry = hash.key?('expiry') ? hash['expiry'] : SKIP
      refresh_token = hash.key?('refresh_token') ? hash['refresh_token'] : SKIP

      # Create object from extracted values.
      OauthToken.new(access_token: access_token,
                     token_type: token_type,
                     expires_in: expires_in,
                     scope: scope,
                     expiry: expiry,
                     refresh_token: refresh_token)
    end

    def self.from_element(root)
      access_token = XmlUtilities.from_element(root, 'access_token', String)
      token_type = XmlUtilities.from_element(root, 'token_type', String)
      expires_in = XmlUtilities.from_element(root, 'expires_in', Integer)
      scope = XmlUtilities.from_element(root, 'scope', String)
      expiry = XmlUtilities.from_element(root, 'expiry', Integer)
      refresh_token = XmlUtilities.from_element(root, 'refresh_token', String)

      new(access_token: access_token,
          token_type: token_type,
          expires_in: expires_in,
          scope: scope,
          expiry: expiry,
          refresh_token: refresh_token)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'access_token', access_token)
      XmlUtilities.add_as_subelement(doc, root, 'token_type', token_type)
      XmlUtilities.add_as_subelement(doc, root, 'expires_in', expires_in)
      XmlUtilities.add_as_subelement(doc, root, 'scope', scope)
      XmlUtilities.add_as_subelement(doc, root, 'expiry', expiry)
      XmlUtilities.add_as_subelement(doc, root, 'refresh_token', refresh_token)

      root
    end
  end
end
