# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # Order Status
  class OrderStatus
    ORDER_STATUS = [
      # TODO: Write general description for PLACED
      PLACED = 'placed'.freeze,

      # TODO: Write general description for APPROVED
      APPROVED = 'approved'.freeze,

      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ORDER_STATUS.include?(value)
    end

    def self.from_value(value, default_value = PLACED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'placed' then PLACED
      when 'approved' then APPROVED
      when 'delivered' then DELIVERED
      else
        default_value
      end
    end
  end
end
