# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
module SwaggerPetstoreOpenApi30
  # Order Model.
  class Order < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :pet_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :ship_date

    # Order Status
    # @return [OrderStatus]
    attr_accessor :status

    # Order Status
    # @return [TrueClass | FalseClass]
    attr_accessor :complete

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['pet_id'] = 'petId'
      @_hash['quantity'] = 'quantity'
      @_hash['ship_date'] = 'shipDate'
      @_hash['status'] = 'status'
      @_hash['complete'] = 'complete'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        pet_id
        quantity
        ship_date
        status
        complete
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, pet_id: SKIP, quantity: SKIP, ship_date: SKIP,
                   status: SKIP, complete: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @id = id unless id == SKIP
      @pet_id = pet_id unless pet_id == SKIP
      @quantity = quantity unless quantity == SKIP
      @ship_date = ship_date unless ship_date == SKIP
      @status = status unless status == SKIP
      @complete = complete unless complete == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      pet_id = hash.key?('petId') ? hash['petId'] : SKIP
      quantity = hash.key?('quantity') ? hash['quantity'] : SKIP
      ship_date = if hash.key?('shipDate')
                    (DateTimeHelper.from_rfc3339(hash['shipDate']) if hash['shipDate'])
                  else
                    SKIP
                  end
      status = hash.key?('status') ? hash['status'] : SKIP
      complete = hash.key?('complete') ? hash['complete'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Order.new(id: id,
                pet_id: pet_id,
                quantity: quantity,
                ship_date: ship_date,
                status: status,
                complete: complete,
                additional_properties: additional_properties)
    end

    def to_custom_ship_date
      DateTimeHelper.to_rfc3339(ship_date)
    end

    def self.from_element(root)
      id = XmlUtilities.from_element(root, 'id', Integer)
      pet_id = XmlUtilities.from_element(root, 'petId', Integer)
      quantity = XmlUtilities.from_element(root, 'quantity', Integer)
      ship_date = XmlUtilities.from_element(root, 'shipDate', String,
                                            datetime_format: 'rfc3339')
      status = XmlUtilities.from_element(root, 'status', String)
      complete = XmlUtilities.from_element(root, 'complete', TrueClass)

      new(id: id,
          pet_id: pet_id,
          quantity: quantity,
          ship_date: ship_date,
          status: status,
          complete: complete,
          additional_properties: additional_properties)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'id', id)
      XmlUtilities.add_as_subelement(doc, root, 'petId', pet_id)
      XmlUtilities.add_as_subelement(doc, root, 'quantity', quantity)
      XmlUtilities.add_as_subelement(doc, root, 'shipDate', ship_date,
                                     datetime_format: 'rfc3339')
      XmlUtilities.add_as_subelement(doc, root, 'status', status)
      XmlUtilities.add_as_subelement(doc, root, 'complete', complete)
      XmlUtilities.add_as_subelement(doc, root, 'additional_properties',
                                     additional_properties)

      root
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, pet_id: #{@pet_id}, quantity: #{@quantity}, ship_date:"\
      " #{@ship_date}, status: #{@status}, complete: #{@complete}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, pet_id: #{@pet_id.inspect}, quantity:"\
      " #{@quantity.inspect}, ship_date: #{@ship_date.inspect}, status: #{@status.inspect},"\
      " complete: #{@complete.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
