# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # Pet Model.
  class Pet < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [Category]
    attr_accessor :category

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :photo_urls

    # TODO: Write general description for this method
    # @return [Array[Tag]]
    attr_accessor :tags

    # pet status in the store
    # @return [PetStatus]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['category'] = 'category'
      @_hash['photo_urls'] = 'photoUrls'
      @_hash['tags'] = 'tags'
      @_hash['status'] = 'status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        category
        tags
        status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name:, photo_urls:, id: SKIP, category: SKIP, tags: SKIP,
                   status: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @id = id unless id == SKIP
      @name = name
      @category = category unless category == SKIP
      @photo_urls = photo_urls
      @tags = tags unless tags == SKIP
      @status = status unless status == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : nil
      photo_urls = hash.key?('photoUrls') ? hash['photoUrls'] : nil
      id = hash.key?('id') ? hash['id'] : SKIP
      category = Category.from_hash(hash['category']) if hash['category']
      # Parameter is an array, so we need to iterate through it
      tags = nil
      unless hash['tags'].nil?
        tags = []
        hash['tags'].each do |structure|
          tags << (Tag.from_hash(structure) if structure)
        end
      end

      tags = SKIP unless hash.key?('tags')
      status = hash.key?('status') ? hash['status'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Pet.new(name: name,
              photo_urls: photo_urls,
              id: id,
              category: category,
              tags: tags,
              status: status,
              additional_properties: additional_properties)
    end

    def self.from_element(root)
      name = XmlUtilities.from_element(root, 'name', String)
      photo_urls = XmlUtilities.from_element_to_array(
        root, 'photoUrl', String, wrapping_element_name: 'photoUrls'
      )
      id = XmlUtilities.from_element(root, 'id', Integer)
      category = XmlUtilities.from_element(root, 'category', Category)
      tags = XmlUtilities.from_element_to_array(root, 'tag', Tag,
                                                wrapping_element_name: 'tags')
      status = XmlUtilities.from_element(root, 'status', String)

      new(name: name,
          photo_urls: photo_urls,
          id: id,
          category: category,
          tags: tags,
          status: status,
          additional_properties: additional_properties)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'name', name)
      XmlUtilities.add_array_as_subelement(doc, root, 'photoUrl', photo_urls,
                                           wrapping_element_name: 'photoUrls')
      XmlUtilities.add_as_subelement(doc, root, 'id', id)
      XmlUtilities.add_as_subelement(doc, root, 'category', category)
      XmlUtilities.add_array_as_subelement(doc, root, 'tag', tags,
                                           wrapping_element_name: 'tags')
      XmlUtilities.add_as_subelement(doc, root, 'status', status)
      XmlUtilities.add_as_subelement(doc, root, 'additional_properties',
                                     additional_properties)

      root
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, name: #{@name}, category: #{@category}, photo_urls:"\
      " #{@photo_urls}, tags: #{@tags}, status: #{@status}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, name: #{@name.inspect}, category: #{@category.inspect},"\
      " photo_urls: #{@photo_urls.inspect}, tags: #{@tags.inspect}, status: #{@status.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
