# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # User Model.
  class User < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :username

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :first_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :last_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :email

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :password

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :phone

    # User Status
    # @return [Integer]
    attr_accessor :user_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['username'] = 'username'
      @_hash['first_name'] = 'firstName'
      @_hash['last_name'] = 'lastName'
      @_hash['email'] = 'email'
      @_hash['password'] = 'password'
      @_hash['phone'] = 'phone'
      @_hash['user_status'] = 'userStatus'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        username
        first_name
        last_name
        email
        password
        phone
        user_status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, username: SKIP, first_name: SKIP, last_name: SKIP,
                   email: SKIP, password: SKIP, phone: SKIP, user_status: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @id = id unless id == SKIP
      @username = username unless username == SKIP
      @first_name = first_name unless first_name == SKIP
      @last_name = last_name unless last_name == SKIP
      @email = email unless email == SKIP
      @password = password unless password == SKIP
      @phone = phone unless phone == SKIP
      @user_status = user_status unless user_status == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      username = hash.key?('username') ? hash['username'] : SKIP
      first_name = hash.key?('firstName') ? hash['firstName'] : SKIP
      last_name = hash.key?('lastName') ? hash['lastName'] : SKIP
      email = hash.key?('email') ? hash['email'] : SKIP
      password = hash.key?('password') ? hash['password'] : SKIP
      phone = hash.key?('phone') ? hash['phone'] : SKIP
      user_status = hash.key?('userStatus') ? hash['userStatus'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      User.new(id: id,
               username: username,
               first_name: first_name,
               last_name: last_name,
               email: email,
               password: password,
               phone: phone,
               user_status: user_status,
               additional_properties: additional_properties)
    end

    def self.from_element(root)
      id = XmlUtilities.from_element(root, 'id', Integer)
      username = XmlUtilities.from_element(root, 'username', String)
      first_name = XmlUtilities.from_element(root, 'firstName', String)
      last_name = XmlUtilities.from_element(root, 'lastName', String)
      email = XmlUtilities.from_element(root, 'email', String)
      password = XmlUtilities.from_element(root, 'password', String)
      phone = XmlUtilities.from_element(root, 'phone', String)
      user_status = XmlUtilities.from_element(root, 'userStatus', Integer)

      new(id: id,
          username: username,
          first_name: first_name,
          last_name: last_name,
          email: email,
          password: password,
          phone: phone,
          user_status: user_status,
          additional_properties: additional_properties)
    end

    def to_xml_element(doc, root_name)
      root = doc.create_element(root_name)

      XmlUtilities.add_as_subelement(doc, root, 'id', id)
      XmlUtilities.add_as_subelement(doc, root, 'username', username)
      XmlUtilities.add_as_subelement(doc, root, 'firstName', first_name)
      XmlUtilities.add_as_subelement(doc, root, 'lastName', last_name)
      XmlUtilities.add_as_subelement(doc, root, 'email', email)
      XmlUtilities.add_as_subelement(doc, root, 'password', password)
      XmlUtilities.add_as_subelement(doc, root, 'phone', phone)
      XmlUtilities.add_as_subelement(doc, root, 'userStatus', user_status)
      XmlUtilities.add_as_subelement(doc, root, 'additional_properties',
                                     additional_properties)

      root
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, username: #{@username}, first_name: #{@first_name}, last_name:"\
      " #{@last_name}, email: #{@email}, password: #{@password}, phone: #{@phone}, user_status:"\
      " #{@user_status}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, username: #{@username.inspect}, first_name:"\
      " #{@first_name.inspect}, last_name: #{@last_name.inspect}, email: #{@email.inspect},"\
      " password: #{@password.inspect}, phone: #{@phone.inspect}, user_status:"\
      " #{@user_status.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
