# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # OrdersApi
  class OrdersApi < BaseApi
    # Creates a new order and triggers callbacks for payment processing
    # @param [CreateOrderRequest] body Required parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_order(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/orders',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Or.new('ApiKey', 'BearerAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Order.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Invalid request',
                                 ErrorException))
        .execute
    end
  end
end
