# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
require 'json'

require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'

require_relative 'webhooks_and_callbacks_api/api_helper'
require_relative 'webhooks_and_callbacks_api/client'

# Utilities
require_relative 'webhooks_and_callbacks_api/utilities/file_wrapper'
require_relative 'webhooks_and_callbacks_api/utilities/date_time_helper'
require_relative 'webhooks_and_callbacks_api/utilities/union_type_lookup'

# Http
require_relative 'webhooks_and_callbacks_api/http/api_response'
require_relative 'webhooks_and_callbacks_api/http/http_call_back'
require_relative 'webhooks_and_callbacks_api/http/http_method_enum'
require_relative 'webhooks_and_callbacks_api/http/http_request'
require_relative 'webhooks_and_callbacks_api/http/http_response'
require_relative 'webhooks_and_callbacks_api/http/proxy_settings'


# Logger
require_relative 'webhooks_and_callbacks_api/logging/configuration/' \
                 'api_logging_configuration'
require_relative 'webhooks_and_callbacks_api/logging/sdk_logger'
require_relative 'webhooks_and_callbacks_api/http/auth/api_key'
require_relative 'webhooks_and_callbacks_api/http/auth/bearer_auth'

# Events
require_relative 'webhooks_and_callbacks_api/events/webhooks/webhooks_handler'
require_relative 'webhooks_and_callbacks_api/events/webhooks/webhooks_a_handler'
require_relative 'webhooks_and_callbacks_api/events/webhooks/webhooks_b_handler'
require_relative 'webhooks_and_callbacks_api/events/webhooks/webhooks_c_handler'
require_relative 'webhooks_and_callbacks_api/events/webhooks/' \
                 'webhooks_no_verification_handler'
require_relative 'webhooks_and_callbacks_api/events/callbacks/' \
                 'callbacks_a_handler'
require_relative 'webhooks_and_callbacks_api/events/callbacks/' \
                 'callbacks_b_handler'
require_relative 'webhooks_and_callbacks_api/events/' \
                 'signature_verification_failure'
require_relative 'webhooks_and_callbacks_api/events/' \
                 'signature_verification_result'
require_relative 'webhooks_and_callbacks_api/events/unknown_event'

# Models
require_relative 'webhooks_and_callbacks_api/models/base_model'
require_relative 'webhooks_and_callbacks_api/models/create_order_request'
require_relative 'webhooks_and_callbacks_api/models/order_item'
require_relative 'webhooks_and_callbacks_api/models/order'
require_relative 'webhooks_and_callbacks_api/models/payment_callback'
require_relative 'webhooks_and_callbacks_api/models/fulfillment_callback'
require_relative 'webhooks_and_callbacks_api/models/email_notification_callback'
require_relative 'webhooks_and_callbacks_api/models/sms_notification_callback'
require_relative 'webhooks_and_callbacks_api/models/notification_callback'
require_relative 'webhooks_and_callbacks_api/models/webhook_registration'
require_relative 'webhooks_and_callbacks_api/models/webhook_update'
require_relative 'webhooks_and_callbacks_api/models/webhook'
require_relative 'webhooks_and_callbacks_api/models/order_created_event'
require_relative 'webhooks_and_callbacks_api/models/order_updated_event'
require_relative 'webhooks_and_callbacks_api/models/payment_completed_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'payment_status_updated_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'payment_status_created_event'
require_relative 'webhooks_and_callbacks_api/models/primitive_collection_event'
require_relative 'webhooks_and_callbacks_api/models/audit_log_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'user_action_notification_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'user_status_notification_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'user_preference_notification_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'system_alert_notification_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'system_maintenance_notification_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'system_performance_notification_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'inventory_stock_increase_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'inventory_stock_decrease_event'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'inventory_stock_depleted_event'
require_relative 'webhooks_and_callbacks_api/models/address'
require_relative 'webhooks_and_callbacks_api/models/delivery_details'
require_relative 'webhooks_and_callbacks_api/models/package'
require_relative 'webhooks_and_callbacks_api/models/oauth_scope_oauth_acg'
require_relative 'webhooks_and_callbacks_api/models/event'
require_relative 'webhooks_and_callbacks_api/models/event_type'
require_relative 'webhooks_and_callbacks_api/models/event_type1'
require_relative 'webhooks_and_callbacks_api/models/event_type2'
require_relative 'webhooks_and_callbacks_api/models/event_type3'
require_relative 'webhooks_and_callbacks_api/models/fulfillment_status'
require_relative 'webhooks_and_callbacks_api/models/fulfillment_statuss'
require_relative 'webhooks_and_callbacks_api/models/payment_status'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'root_level_primitive_one_of_event_request'
require_relative 'webhooks_and_callbacks_api/models/' \
                 'root_level_primitive_one_of_event_request1'
require_relative 'webhooks_and_callbacks_api/models/status'
require_relative 'webhooks_and_callbacks_api/models/status1'
require_relative 'webhooks_and_callbacks_api/models/status2'

# Exceptions
require_relative 'webhooks_and_callbacks_api/exceptions/api_exception'
require_relative 'webhooks_and_callbacks_api/exceptions/error_exception'

require_relative 'webhooks_and_callbacks_api/configuration'

# Controllers
require_relative 'webhooks_and_callbacks_api/apis/base_api'
require_relative 'webhooks_and_callbacks_api/apis/orders_api'
