# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # CallbacksAHandler is responsible for verifying request signatures
  # and parsing incoming callbacksA events into strongly typed objects.
  class CallbacksAHandler
    include CoreLibrary
    # Creates a new instance of the CallbacksAHandler.
    # Initializes the handler.
    # @param [String] secret_key
    # The secret used to generate and validate HMAC signatures for verifying request authenticity.
    # @raise [ArgumentError] If the secret_key is not provided.
    def initialize(secret_key)
      raise ArgumentError, 'secret_key must be provided for signature verification.' unless secret_key

      @verifier = HmacSignatureVerifier.new(
        secret_key: secret_key,
        signature_header: 'X-Signature',
        hash_algorithm: 'sha256',
        encoder: HexEncoder.new
      )
    end

    # Perform signature verification and return the result.
    #
    # @param [Rack::Request] request The incoming HTTP request to verify.
    # @return [SignatureVerificationResult] The result of the signature verification.
    def verify(request)
      @verifier.verify(request)
    end

    # Verify the request signature and parse the event.
    #
    # @param [Rack::Request] request The incoming HTTP request containing the event payload.
    # @return[PaymentCallback, FulfillmentCallback,
    # SignatureVerificationFailure, UnknownEvent]
    # PaymentCallback, FulfillmentCallback for successful parsing;
    #
    # SignatureVerificationFailure when signature fails;
    # UnknownEvent for
    # unknown events.
    def verify_and_parse_event(request)
      unless request.respond_to?(:env) && request.env.is_a?(Hash)
        return SignatureVerificationFailure.new(['Invalid request env.'])
      end

      raw_body = RackRequestHelper.read_raw_body(request)
      return SignatureVerificationFailure.new(['Invalid request body.']) if raw_body.nil? || raw_body.empty?

      verification_result = verify(request)
      return SignatureVerificationFailure.new(verification_result.errors) unless verification_result.ok

      # Deserialize payload
      begin
        union = UnionTypeLookUp.get(:CallbacksA)
        raw = RackRequestHelper.read_raw_body(request)
        APIHelper.deserialize_union_type(union, raw, false, true)
      rescue StandardError => e
        UnknownEvent.new(['Deserialization failed.', e.message])
      end
    end
  end
end
