# swagger_petstore_open_api30
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module SwaggerPetstoreOpenApi30
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
