# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # The `UnionTypeLookUp` class serves as a utility class for
  # storing and managing type combinator templates. It acts as a container for the templates
  # used in handling various oneof/anyof instances within the sdk.
  class UnionTypeLookUp
    include CoreLibrary
    # rubocop:disable Lint/RedundantCopDisableDirective, Style/HashSyntax, Layout/FirstArgumentIndentation
    def self.union_types
      {
        :UserNotificationEventBody => OneOf.new(
          [
            LeafType.new(UserActionNotificationEvent),
            LeafType.new(UserStatusNotificationEvent),
            LeafType.new(UserPreferenceNotificationEvent)
          ]
        ),

        :SystemNotificationEventBody => OneOf.new(
          [
            LeafType.new(SystemAlertNotificationEvent),
            LeafType.new(SystemMaintenanceNotificationEvent),
            LeafType.new(SystemPerformanceNotificationEvent)
          ]
        ),

        :InventoryChangeEventBody => OneOf.new(
          [
            LeafType.new(InventoryStockIncreaseEvent),
            LeafType.new(InventoryStockDecreaseEvent),
            LeafType.new(InventoryStockDepletedEvent)
          ]
        ),

        :RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody => OneOf.new(
          [
            LeafType.new(RootLevelPrimitiveOneOfEventRequest),
            LeafType.new(Integer),
            LeafType.new(RootLevelPrimitiveOneOfEventRequest1, UnionTypeContext.new(
              is_array: true
            )),
            LeafType.new(Integer, UnionTypeContext.new(
              is_array: true
            ))
          ]
        ),

        :FulfillmentCallbackDeliveryDetails => OneOf.new(
          [
            LeafType.new(String),
            LeafType.new(DeliveryDetails)
          ],
          UnionTypeContext.new(
            is_optional: true
          )
        ),

        :OrderCreatedEventDeliveryDetails => OneOf.new(
          [
            LeafType.new(String),
            LeafType.new(DeliveryDetails)
          ],
          UnionTypeContext.new(
            is_optional: true
          )
        ),

        :Webhooks => OneOf.new(
          [
            LeafType.new(OrderCreatedEvent),
            LeafType.new(OrderUpdatedEvent),
            LeafType.new(PaymentCompletedEvent),
            LeafType.new(PrimitiveCollectionEvent)
          ]
        ),

        :WebhooksA => OneOf.new(
          [
            LeafType.new(PaymentStatusUpdatedEvent),
            LeafType.new(PaymentStatusCreatedEvent)
          ]
        ),

        :WebhooksB => OneOf.new(
          [
            OneOf.new(
          [
            LeafType.new(UserActionNotificationEvent),
            LeafType.new(UserStatusNotificationEvent),
            LeafType.new(UserPreferenceNotificationEvent)
          ]
        ),
            OneOf.new(
          [
            LeafType.new(SystemAlertNotificationEvent),
            LeafType.new(SystemMaintenanceNotificationEvent),
            LeafType.new(SystemPerformanceNotificationEvent)
          ]
        ),
            OneOf.new(
          [
            LeafType.new(InventoryStockIncreaseEvent),
            LeafType.new(InventoryStockDecreaseEvent),
            LeafType.new(InventoryStockDepletedEvent)
          ]
        )
          ]
        ),

        :WebhooksC => OneOf.new(
          [
            LeafType.new(String),
            LeafType.new(Integer),
            LeafType.new(Float, UnionTypeContext.new(
              is_array: true
            )),
            LeafType.new(String, UnionTypeContext.new(
              is_dict: true
            ))
          ]
        ),

        :WebhooksNoVerification => OneOf.new(
          [
            LeafType.new(AuditLogEvent),
            OneOf.new(
          [
            LeafType.new(RootLevelPrimitiveOneOfEventRequest),
            LeafType.new(Integer),
            LeafType.new(RootLevelPrimitiveOneOfEventRequest1, UnionTypeContext.new(
              is_array: true
            )),
            LeafType.new(Integer, UnionTypeContext.new(
              is_array: true
            ))
          ]
        )
          ]
        ),

        :CallbacksA => OneOf.new(
          [
            LeafType.new(PaymentCallback),
            LeafType.new(FulfillmentCallback)
          ]
        ),

        :CallbacksB => OneOf.new(
          [
            LeafType.new(NotificationCallback, UnionTypeContext.new(
              discriminator_value: 'email',
              discriminator: 'notificationType'
            )),
            LeafType.new(NotificationCallback, UnionTypeContext.new(
              discriminator_value: 'sms',
              discriminator: 'notificationType'
            ))
          ]
        )
      }
    end
    # rubocop:enable Lint/RedundantCopDisableDirective, Style/HashSyntax, Layout/FirstArgumentIndentation

    def self.get(name)
      UnionTypeLookUp.union_types[name]
    end
  end
end
