# webhooks_and_callbacks_api
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module WebhooksAndCallbacksApi
  # HttpCallBack allows defining callables for pre and post API calls.
  class HttpCallBack < CoreLibrary::HttpCallback
  end
end
