# cypress_test_api
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module CypressTestApi
  # CustomEnum.
  class CustomEnum
    CUSTOM_ENUM = [
      # TODO: Write general description for VALUE1
      VALUE1 = 'VALUE1'.freeze,

      # TODO: Write general description for VALUE2
      VALUE2 = 'VALUE2'.freeze,

      # TODO: Write general description for VALUE3
      VALUE3 = 'VALUE3'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CUSTOM_ENUM.include?(value)
    end

    def self.from_value(value, default_value = VALUE1)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'value1' then VALUE1
      when 'value2' then VALUE2
      when 'value3' then VALUE3
      else
        default_value
      end
    end
  end
end
