# cypress_test_api
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module CypressTestApi
  # OAuth 2 scopes supported by the API
  class OAuthScopeOAuthACGEnum
    O_AUTH_SCOPE_O_AUTH_ACG_ENUM = [
      # TODO: Write general description for ENUM_FILE_REQUESTSREAD
      ENUM_FILE_REQUESTSREAD = 'file_requests.read'.freeze,

      # TODO: Write general description for ZAHRA
      ZAHRA = 'zahra'.freeze,

      # TODO: Write general description for TEST1
      TEST1 = 'test1'.freeze,

      # TODO: Write general description for SELECTION
      SELECTION = 'selection'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      O_AUTH_SCOPE_O_AUTH_ACG_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ENUM_FILE_REQUESTSREAD)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enum_file_requestsread' then ENUM_FILE_REQUESTSREAD
      when 'zahra' then ZAHRA
      when 'test1' then TEST1
      when 'selection' then SELECTION
      else
        default_value
      end
    end
  end
end
