# cypress_test_api
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module CypressTestApi
  # Status.
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for ACTIVE
      ACTIVE = 'active'.freeze,

      # TODO: Write general description for INACTIVE
      INACTIVE = 'inactive'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ACTIVE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'active' then ACTIVE
      when 'inactive' then INACTIVE
      when 'pending' then PENDING
      else
        default_value
      end
    end
  end
end
